#!/bin/sh
# Install Shake&Tune Remote macros on a Creality K1/K1C/K1 Max
#
# Run on the K1 via SSH:
#   sh install.sh <server_host> <server_port> <printer_name> [base_url]
#
# Example:
#   sh install.sh 192.168.40.11 3080 k1v3
#   sh install.sh 192.168.40.11 3080 k1v3 https://shaketune.iflorian.com
#
# What this does:
#   1. Copies scripts to /usr/data/printer_data/config/shaketune/scripts/
#   2. Generates shaketune.cfg with your server/printer settings
#   3. Adds [include shaketune.cfg] to printer.cfg if not already present
#   4. Prompts you to restart Klipper

set -e

HOST="${1:?Usage: install.sh <host> <port> <printer_name> [base_url]}"
PORT="${2:?Usage: install.sh <host> <port> <printer_name> [base_url]}"
PRINTER="${3:?Usage: install.sh <host> <port> <printer_name> [base_url]}"
BASE_URL="${4:-http://${HOST}:${PORT}}"

CONFIG_DIR="/usr/data/printer_data/config"
SCRIPTS_DIR="${CONFIG_DIR}/shaketune/scripts"
CFG_FILE="${CONFIG_DIR}/shaketune.cfg"
PRINTER_CFG="${CONFIG_DIR}/printer.cfg"

# Detect script source directory (where this install.sh lives)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

echo "=== Shake&Tune Remote Installer ==="
echo "Server:   ${HOST}:${PORT}"
echo "Base URL: ${BASE_URL}"
echo "Printer:  ${PRINTER}"
echo ""

# 1. Copy scripts
echo "[1/3] Installing scripts..."
mkdir -p "${SCRIPTS_DIR}"
cp "${SCRIPT_DIR}/scripts/upload_shaper.sh" "${SCRIPTS_DIR}/"
cp "${SCRIPT_DIR}/scripts/upload_belts.sh" "${SCRIPTS_DIR}/"
cp "${SCRIPT_DIR}/scripts/run_belts.sh" "${SCRIPTS_DIR}/"
chmod +x "${SCRIPTS_DIR}"/*.sh
echo "  -> ${SCRIPTS_DIR}/"

# 2. Generate shaketune.cfg with printer-specific values
echo "[2/3] Generating ${CFG_FILE}..."
cat > "${CFG_FILE}" << ENDCFG
########################################
# Shake&Tune Remote Service Macros
########################################
#
# Auto-generated by install.sh
# Server: ${HOST}:${PORT}  Printer: ${PRINTER}
#
# Macros:
#   SHAKETUNE_SHAPER_REMOTE  - Input shaper calibration (X+Y axes)
#   SHAKETUNE_BELTS_REMOTE   - Belt tension comparison (with firmware restart)
#   SHAKETUNE_EXCITE_REMOTE  - Vibrate at specific frequency for diagnosis
#
########################################

[respond]

[gcode_macro _SHAKETUNE_REMOTE_CONFIG]
description: Configuration for remote Shake&Tune service
variable_host: "${HOST}"
variable_port: "${PORT}"
variable_printer: "${PRINTER}"
variable_base_url: "${BASE_URL}"
gcode:
  # This macro just holds configuration variables


# Shell command for shaper upload
[gcode_shell_command shaketune_upload_shaper_remote]
command: sh -c 'BASE_URL=${BASE_URL} sh ${SCRIPTS_DIR}/upload_shaper.sh ${HOST} ${PORT} ${PRINTER}'
timeout: 120
verbose: True

# Shell command for belts - launches orchestrator detached from Klipper
# (must be detached via setsid because the script does a firmware restart
# mid-run, which would kill a Klipper-owned child process)
[gcode_shell_command shaketune_run_belts_remote]
command: sh -c 'setsid sh -c "BASE_URL=${BASE_URL} sh ${SCRIPTS_DIR}/run_belts.sh ${HOST} ${PORT} ${PRINTER}" > /tmp/shaketune_belts.log 2>&1 &'
timeout: 10
verbose: True


[gcode_macro SHAKETUNE_SHAPER_REMOTE]
description: Run input shaper calibration and generate analysis graph via remote service
gcode:
  {% if printer.toolhead.homed_axes != "xyz" %}
    RESPOND MSG="Homing..."
    G28
  {% endif %}
  G0 X{printer.toolhead.axis_maximum.x / 2} Y{printer.toolhead.axis_maximum.y / 2} Z50 F6000
  RESPOND MSG="Testing X axis resonances..."
  TEST_RESONANCES AXIS=X OUTPUT=raw_data NAME=x
  M400
  RESPOND MSG="Testing Y axis resonances..."
  TEST_RESONANCES AXIS=Y OUTPUT=raw_data NAME=y
  M400
  RESPOND MSG="Uploading to remote Shake&Tune service..."
  RUN_SHELL_COMMAND CMD=shaketune_upload_shaper_remote
  RESPOND MSG="Analysis complete! Check console for graph URL."


[gcode_macro SHAKETUNE_BELTS_REMOTE]
description: Run belt comparison test and generate analysis graph via remote service
gcode:
  # The belt test is fully orchestrated by a shell script via Moonraker API.
  # It runs Belt A, does a firmware restart (to avoid K1 move queue overflow
  # with raw data), re-homes, runs Belt B, then uploads both CSVs.
  # Progress is logged to /tmp/shaketune_belts.log
  RESPOND MSG="Starting belt comparison (with firmware restart between sweeps)..."
  RESPOND MSG="This will take ~6 minutes. Progress is in /tmp/shaketune_belts.log"
  RUN_SHELL_COMMAND CMD=shaketune_run_belts_remote


[gcode_macro SHAKETUNE_EXCITE_REMOTE]
description: Vibrate at a specific frequency to locate resonance sources
gcode:
  {% set frequency = params.FREQUENCY|default(25)|int %}
  {% set duration = params.DURATION|default(10)|int %}
  {% set axis = params.AXIS|default("x")|string|lower %}
  {% if axis == "a" %}
    {% set axis = "1,-1" %}
  {% elif axis == "b" %}
    {% set axis = "1,1" %}
  {% endif %}
  {% if printer.toolhead.homed_axes != "xyz" %}
    RESPOND MSG="Homing..."
    G28
  {% endif %}
  G0 X{printer.toolhead.axis_maximum.x / 2} Y{printer.toolhead.axis_maximum.y / 2} Z50 F6000
  RESPOND MSG="Exciting {axis} axis at {frequency}Hz for {duration}s..."
  TEST_RESONANCES OUTPUT=raw_data AXIS={axis} FREQ_START={frequency - 1} FREQ_END={frequency + 1} HZ_PER_SEC={1 / (duration / 3)}
  M400
  RESPOND MSG="Done."
ENDCFG
echo "  -> ${CFG_FILE}"

# 3. Add include to printer.cfg if needed
echo "[3/3] Checking printer.cfg..."
if grep -q "include shaketune.cfg" "${PRINTER_CFG}"; then
  echo "  -> Already included in printer.cfg"
else
  # Add after the last [include ...] line
  sed -i '/^\[include /!b; :a; n; /^\[include /ba; i\[include shaketune.cfg]' "${PRINTER_CFG}" 2>/dev/null || {
    # Fallback: just append near the top includes
    echo "[include shaketune.cfg]" >> "${PRINTER_CFG}"
  }
  echo "  -> Added [include shaketune.cfg] to printer.cfg"
fi

echo ""
echo "=== Installation complete ==="
echo ""
echo "Restart Klipper to activate:"
echo "  FIRMWARE_RESTART"
echo ""
echo "Then run:"
echo "  SHAKETUNE_SHAPER_REMOTE   - Input shaper graphs"
echo "  SHAKETUNE_BELTS_REMOTE    - Belt comparison graph"
echo "  SHAKETUNE_EXCITE_REMOTE   - Vibrate at frequency"
echo ""
echo "Results at: ${BASE_URL}/"
